version: '2'

services:
  ldev-lalamove-api:
    #extends:
    #  file: ./service-common/docker-compose/nodejs-service.yml
    #  service: nodejs-service
    image: test1
    hostname: ldev-lalamove-api 
    ports:
      - "20030:80" 
    environment:
      - VIRTUAL_HOST=ldev-api.lalamove.com 
      - VIRTUAL_PORT=80
      - PORT=80
      - NODE_ENV=ldev 
      - INSTALL_VENDORS=0
    networks:
      - ldev-backend 
networks:
  ldev-backend:
    external:
      name: ldev-backend
